// frontend/fakeProposals.js
export const fakeProposals = [
  {
    id: 1,
    userName: "John Doe",
    userInitials: "JD",
    time: "2025-09-24T12:00:00Z",
    title: "Fake Proposal 1",
    text: "This is a fake proposal",
    author_img: "",
    author_type: "human",
    media: { image: "", video: "", link: "", file: "" },
    likes: [],
    dislikes: [],
    comments: [],
  },
  {
    id: 2,
    userName: "Jane Smith",
    userInitials: "JS",
    time: "2025-09-24T13:00:00Z",
    title: "Fake Proposal 2",
    text: "Another fake proposal",
    author_img: "",
    author_type: "ai",
    media: { image: "", video: "", link: "", file: "" },
    likes: [],
    dislikes: [],
    comments: [],
  },
];